### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by handlers**

### CODE REVIEW

**Comment by jamesturk** [comment]
thanks Sam

**Comment by handlers** [comment]
:+1:

**Comment by jamesturk** [comment]
did I upset @paultag?

**Comment by paultag** [comment]
:heart:

On Fri, Feb 20, 2015 at 11:32 AM, James Turk <notifications@github.com>
wrote:

> did I upset @paultag <https://github.com/paultag>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/opencivicdata.org/pull/20#issuecomment-75267977>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by paultag** [comment]
one day i'll get to use [revu](https://github.com/paultag/revu) :)

**Pull request merged**
